# -*- coding: utf-8 -*-
"""DSBDA Mini Project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nCZk8EVNeIwA72ZN8wS06x0_B77z-u4K
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("DSBDAL Uncleaned Data.csv")
df

ndf=df
ndf.fillna(0)

m_v=df['Age'].median()
df['Age'].fillna(value=m_v, inplace=True)
df

ndf.dropna()

missing_value_per = ndf.isnull().sum()/ndf.shape[0] * 100
missing_value_per

missing_value_clm_gre_20 = missing_value_per[missing_value_per > 20].keys()
missing_value_clm_gre_20

df2_drop_clm = df.drop(columns=missing_value_clm_gre_20)
df2_drop_clm.shape

df2_drop_clm

m_v1=df2_drop_clm['Annual Income'].mean()
df2_drop_clm['Annual Income'].fillna(value=m_v1, inplace=True)
df2_drop_clm

df2_drop_clm.to_excel("DSBDAL Cleaned Data.xlsx")

import seaborn as sns

df2_drop_clm['Age'].plot(kind = 'hist')

def bar_graph(feature):
    df[feature].value_counts().plot(kind="bar")

plt.figure(figsize=(15,3))
bar_graph('Gender')

bar_graph('Profession')

bar_graph('Annual Income')